# Generated by Django 3.2.5 on 2022-05-07 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0012_alter_extendeduser_notification_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='latest_notify',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
